# Generated by Django 4.2.3 on 2024-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'No category'), ('IT', 'IT'), ('Hobby', 'Hobby'), ('Videogames', 'Videogames')], max_length=32, null=True),
        ),
    ]
