# Generated by Django 4.2.3 on 2024-09-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'No category'), ('it', 'IT'), ('hobby', 'Hobby'), ('videogames', 'Videogames')], max_length=32, null=True),
        ),
    ]
